site_url: https://mikeneumegen.com
site_name: Mike Neumegen
site_title: Mike Neumegen
favicon: "/images/favicon.svg"
description: The personal website of Mike Neumegen, Cofounder and CEO of CloudCannon.
twitter_site: "@mikeneumegen"
image: 
image_alt:
